Module2 task1
htmlacademy-adaptive/1408611-cat-energy-21 pull request #2
Opened 2020-11-15 17:19 UTC by ayqod

2020-11-15 19:10 UTC, Shramkoweb requested changes

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +        <a href="form.html" class="promo__link">Подобрать программу</a>
`class="promo__link` выности в самое начало тега

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +            <p class="example-item__title">снижение веса</p>
Можно улучшить семантику и сделать dd & dt ?

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +          <span class="example__price example__price--value">15000 руб.</span>
`example__price` елмент внутри елемента `example__price` ?

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +          <img class="example__image example__image--before" src="https://via.placeholder.com/311x232"
`example__image` елмент внутри елемента `example__image`?

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +          <button class="changes__btn changes__btn--before" type="button">Было</button>
btn -> button

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +        <div class="contacts__text">
contacts__inner ? Это же обертка, а не текст

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +          <iframe class="contacts__map contacts__map--frame" src="https://maps.google.com/maps?width=320&amp;height=362&amp;hl=en&amp;q=%D1%83%D0%BB.%20%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B0%D1%8F%20%D
Опять елемент внутри елемента

2020-11-15 19:10 UTC, Shramkoweb commented on source/index.html
> +        <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive"></a>
Это все одна ссылка =) 

Зачем мне 2 ссылки которые ведут в одно место?

2020-11-15 19:20 UTC, ayqod commented on source/index.html
> +        <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive"></a>
Аа, это по дизу такой единый логотип...понятно)

2020-11-15 19:24 UTC, ayqod commented on source/index.html
> +        <a href="form.html" class="promo__link">Подобрать программу</a>
✅

2020-11-15 19:29 UTC, ayqod commented on source/index.html
> +          <span class="example__price example__price--value">15000 руб.</span>
а элемент-мод внутри элемента может быть? У меня изначально так было, но валидатор yoksel тот не пропускал. А вот так он почему-то пропутстил:)

2020-11-15 19:31 UTC, ayqod commented on source/index.html
> +          <img class="example__image example__image--before" src="https://via.placeholder.com/311x232"
Та же самая ситуация, что выше описал по валидатору yoksel)

2020-11-15 19:33 UTC, ayqod commented on source/index.html
> +          <span class="example__price example__price--value">15000 руб.</span>
```
<p class="example__price">	        
          Затраты на питание:
          <span class="example__price--value">15000 руб.</span>
 </p>
```
Вот так я делал до валидатора

2020-11-15 19:34 UTC, ayqod commented on source/index.html
> +          <iframe class="contacts__map contacts__map--frame" src="https://maps.google.com/maps?width=320&amp;height=362&amp;hl=en&amp;q=%D1%83%D0%BB.%20%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B0%D1%8F%20%D
Это все валидатор виноват) Шучу, но ситуация такая же и сам не понял почему мой первый вариант он не пропускал, а уот это уот -- пожалуйста, пропустил:)

2020-11-15 20:05 UTC, Shramkoweb commented on source/index.html
> +          <span class="example__price example__price--value">15000 руб.</span>
Так тоже нельзя модификатор может быть на узле где есть блок или елемент

2020-11-15 22:05 UTC, ayqod commented on source/index.html
> +          <span class="example__price example__price--value">15000 руб.</span>
А если не миксовать, то от example__price ниже будет идти example__price-value

так можно?

2020-11-15 22:06 UTC, ayqod commented on source/index.html
> +          <button class="changes__btn changes__btn--before" type="button">Было</button>
✅ думал btn общепринятое сокращение, поэтому допустимо(

2020-11-15 22:40 UTC, ayqod commented on source/index.html
> +        <div class="contacts__text">
✅ oops

2020-11-15 22:41 UTC, ayqod commented on source/index.html
> +          <iframe class="contacts__map contacts__map--frame" src="https://maps.google.com/maps?width=320&amp;height=362&amp;hl=en&amp;q=%D1%83%D0%BB.%20%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B0%D1%8F%20%D
✅

2020-11-16 18:53 UTC, Shramkoweb approved these changes

2020-11-16 18:53 UTC, merged