4. Разметка страницы каталога
htmlacademy-adaptive/1408611-cat-energy-21 pull request #4
Opened 2020-11-18 19:28 UTC by ayqod

2020-11-18 20:00 UTC, Shramkoweb requested changes

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +            <a class="nav-list__link nav-list__item--active" href="catalog.html">Каталог продукции</a>
Мы уже на каталоге =)

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +
Немного не понял твоего патерна отступов? Расскажешь?

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +            <a class="catalog__order button" href="order.html">Заказать</a>
А почему это элемент каталога? Это же кнопка каждой li ?

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +                <td class="extra-item__info-count">
extra-item__count ?

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +                <td class="extra-item__info-price">
extra-item__price ?

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +          <img class="contacts-map__img" src="https://via.placeholder.com/320x362" alt="Адрес: ул. Большая Конюшенная, д. 19/8 Санкт-Петербург">
Можно сразу обернуть в [noscript](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript)

2020-11-18 20:00 UTC, Shramkoweb commented on source/catalog.html
> +      <a class="page-footer__logo" href="">
Ссылка на главную

2020-11-18 20:43 UTC, ayqod commented on source/catalog.html
> +            <a class="nav-list__link nav-list__item--active" href="catalog.html">Каталог продукции</a>
✅

2020-11-18 20:47 UTC, ayqod commented on source/catalog.html
> +
✅ Поменял

Типа "смотрите какой у меня alt текст клевый", чтобы строка не такая длинная была и видеть, что он уже на месте есть)

2020-11-18 20:49 UTC, ayqod commented on source/catalog.html
> +            <a class="catalog__order button" href="order.html">Заказать</a>
✅

2020-11-18 20:51 UTC, ayqod commented on source/catalog.html
> +                <td class="extra-item__info-count">
Це генiально)

2020-11-18 20:55 UTC, ayqod commented on source/catalog.html
> +                <td class="extra-item__info-price">
при этом ниже я уже теряю смиксованный extra-item и навешиваю просто элементы на блок экстра...вроде это неправильно тоже?

2020-11-18 20:58 UTC, ayqod commented on source/catalog.html
> +      <a class="page-footer__logo" href="">
✅

2020-11-18 21:01 UTC, ayqod commented on source/catalog.html
> +          <img class="contacts-map__img" src="https://via.placeholder.com/320x362" alt="Адрес: ул. Большая Конюшенная, д. 19/8 Санкт-Петербург">
✅

2020-11-18 21:09 UTC, ayqod commented on source/catalog.html
> +                <td class="extra-item__info-price">
А там уже и extra__link  у меня пошел вместо extra-item__link ^) Исправил заодно и это тоже

2020-11-19 17:20 UTC, Shramkoweb requested changes

2020-11-19 17:20 UTC, Shramkoweb commented on source/catalog.html
> +          <img class="contacts-map__img" src="https://via.placeholder.com/320x362" alt="Адрес: ул. Большая Конюшенная, д. 19/8 Санкт-Петербург">
noscript ты оборачиваешь, то что хочешь загрузить без JS. У нас это картинка, а ты сделал наоборрот)

2020-11-19 17:21 UTC, ayqod commented on source/catalog.html
> +          <img class="contacts-map__img" src="https://via.placeholder.com/320x362" alt="Адрес: ул. Большая Конюшенная, д. 19/8 Санкт-Петербург">
🤦‍♂️

2020-11-19 17:21 UTC, Shramkoweb requested changes

2020-11-19 17:21 UTC, Shramkoweb commented on source/form.html
> +                <label class="form__label" for="keeper-phone">Телефон:<sup>*</sup></label>
<sup>*</sup>  - это про верхни индекс семантически. 
Тут просто звездочка, это немного не про то

2020-11-19 17:26 UTC, ayqod commented on source/form.html
> +                <label class="form__label" for="keeper-phone">Телефон:<sup>*</sup></label>
В демке они тоже самое делали же...

2020-11-19 17:43 UTC, merged